server:
  port: 20004
spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hdsx?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
# dubbo
dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: com.hdsx.dubbo.user.impl.service
  provider:
    filter: -exception
    UserService:
      version: 1.0.0
# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: user-producer-spu-collection-group
